# Generated by Django 5.2.7 on 2025-10-03 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasas', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ejercicio ligero'), ('moderado', 'Ejercicio moderado'), ('intenso', 'Ejercicio intenso'), ('atleta', 'Atleta')], max_length=20)),
                ('objetivo', models.CharField(choices=[('perder', 'Perder peso'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar masa muscular')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_diarias', models.FloatField()),
                ('proteinas_diarias', models.FloatField()),
                ('carbohidratos_diarias', models.FloatField()),
                ('grasas_diarias', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('cantidad', models.FloatField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.alimento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.plannutricional')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaAlimenticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('gusta', 'Me gusta'), ('no_gusta', 'No me gusta'), ('alergia', 'Alergia')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
