# Generated by Django 5.2.7 on 2025-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(choices=[('proteina', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('grasa', 'Grasa Saludable'), ('vegetal', 'Vegetal'), ('fruta', 'Fruta'), ('lacteo', 'Lácteo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_actividad',
            field=models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ejercicio ligero (1-2 días/semana)'), ('moderado', 'Ejercicio moderado (3-5 días/semana)'), ('intenso', 'Ejercicio intenso (6-7 días/semana)'), ('atleta', 'Atleta (2 veces al día)')], max_length=20),
        ),
    ]
